"""
Django settings for Generator project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# .env: в папке Generator/ или в корне проекта (например /opt/generator/.env)
load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR.parent / ".env")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# В production задайте SECRET_KEY через переменную окружения
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-)&u-i%%%7kr6y6kx11pcr$fq6e1ita5)%ykv1aluxmvtbaln#7')

# Общий секрет с ЛК для JWT входа в урок (/lesson/join/). В .env: LESSON_SECRET=...
LESSON_SECRET = os.environ.get("LESSON_SECRET", "").strip()

LK_PUBLIC_URL = os.environ.get("LK_PUBLIC_URL", "https://lk.genurok.tw1.ru").rstrip("/")
LK_LESSON_NOTIFY_URL = os.environ.get("LK_LESSON_NOTIFY_URL", "").strip()
# Кнопка «Личный кабинет»: если переменная не задана — пароль 100326; пустая строка LK_NAVIGATION_PASSWORD= — без пароля.
_lk_nav_env = os.environ.get("LK_NAVIGATION_PASSWORD")
if _lk_nav_env is None:
    LK_NAVIGATION_PASSWORD = "100326"
else:
    LK_NAVIGATION_PASSWORD = _lk_nav_env.strip()

DEBUG = os.environ.get('DEBUG', 'true').lower() == 'true'
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'Generator.apps.GeneratorConfig',
    'Board',
    'corsheaders',
    "django_ckeditor_5",
]
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "bold", "italic",
            "link",
            "bulletedList", "numberedList",
            "imageUpload",
            "undo", "redo"
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "imageStyle:full",
                "imageStyle:side"
            ]
        },
    }
}
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 2. Session — до Common
    "django.middleware.common.CommonMiddleware",  # 3. Common — один раз
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

_extra_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://localhost:5001",
    "http://127.0.0.1:5001",
    # ЛК локально
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
    "https://*.replit.dev",
    "https://*.repl.co",
] + [o.strip() for o in _extra_origins.split(',') if o.strip()]

CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # React должен читать cookie
SESSION_COOKIE_SAMESITE = 'Lax'

ROOT_URLCONF = 'Generator.urls'

FRONTEND_DIR = Path(__file__).resolve().parent.parent.parent / 'frontend' / 'dist'
# frontend/dist появляется после npm run build
TEMPLATE_DIRS = [FRONTEND_DIR] if FRONTEND_DIR.exists() else []

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    }
]

WSGI_APPLICATION = 'Generator.wsgi.application'
ASGI_APPLICATION = "Generator.asgi.application"

# WebSocket уроков: redis — для нескольких воркеров; inmemory — один процесс Daphne, Redis не нужен.
_channel_backend = (os.environ.get("CHANNEL_LAYER_BACKEND") or "redis").strip().lower()
if _channel_backend in ("inmemory", "memory", "local"):
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
else:
    _redis_host = os.environ.get("REDIS_HOST", "127.0.0.1")
    _redis_port = int(os.environ.get("REDIS_PORT", "6379"))
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [(_redis_host, _redis_port)]},
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# В systemd задают PGDATABASE/PGUSER/... — обязательно читаем их (раньше были захардкожены generatordb).
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("PGDATABASE", "generatordb"),
#         "USER": os.environ.get("PGUSER", "generator_user"),
#         "PASSWORD": os.environ.get("PGPASSWORD", "StrongPass123"),
#         "HOST": os.environ.get("PGHOST", "localhost"),
#         "PORT": os.environ.get("PGPORT", "5432"),
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("PGDATABASE", "generatordb"),
        "USER": os.environ.get("PGUSER", "postgres"),
        "PASSWORD": os.environ.get("PGPASSWORD", "postgres"),
        "HOST": os.environ.get("PGHOST", "localhost"),
        "PORT": os.environ.get("PGPORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"] + ([FRONTEND_DIR] if FRONTEND_DIR.exists() else [])
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Telegram bot для отправки сообщений об ошибках
# Для группового чата: добавьте бота в группу, затем получите ID через
# https://api.telegram.org/bot<TOKEN>/getUpdates после сообщения в группе.
# ID группы — отрицательное число, например: -1001234567890
# TELEGRAM_TOPIC_ID — ID топика (для групп с темами). Число из URL топика.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '')
TELEGRAM_TOPIC_ID = os.environ.get('TELEGRAM_TOPIC_ID', '') or None  # опционально

