"""
Django settings for Cabinet project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.contrib import admin
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Сначала .env (база для всех сред). .env.local только для машины разработчика и перекрывает .env.
# Важно: при старом порядке (.env.local → .env) второй файл НЕ перезаписывал уже заданные ключи —
# на сервере лишний .env.local мог уводить проект на «чужую» БД.
load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR / ".env.local", override=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-0!^zwlov_t=@x1w^im@mgral)1s*+6xw*wy_e^lxa_i-if##y%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000').rstrip('/')
# Пока ЛК без TLS: в .env мог остаться https:// — принудительно http (или просто поправьте FRONTEND_URL на http://...)
if os.environ.get('FRONTEND_URL_FORCE_HTTP', '').lower() in ('1', 'true', 'yes'):
    if FRONTEND_URL.lower().startswith('https://'):
        FRONTEND_URL = 'http://' + FRONTEND_URL[8:]

# URL сайта генератора уроков (ссылки lesson/join в JWT). В .env задавайте GENUROK_URL латиницей.
_LEGACY_GENUROK_KEY = 'GENUR\u041e\u041a_URL'  # старый ключ с кирилл. О и К (если остался на сервере)
_genurok_raw = (os.environ.get('GENUROK_URL') or os.environ.get(_LEGACY_GENUROK_KEY) or 'https://genurok.tw1.ru')
GENUROK_URL = _genurok_raw.strip().rstrip('/')
# После /logout/ — по умолчанию страница входа (`/login/` на хосте FRONTEND_URL). Иначе задайте LOGOUT_REDIRECT_URL.
_logout_url = os.environ.get('LOGOUT_REDIRECT_URL', '').strip().rstrip('/')
LOGOUT_REDIRECT_URL = _logout_url if _logout_url else f"{FRONTEND_URL}/login/"
# Общий секрет с ГенУрок.рф для подписи JWT. В проде задайте через env-переменную.
LESSON_SECRET = os.environ.get('LESSON_SECRET', SECRET_KEY)
# Видео в JWT: свой сервер Jitsi. Переопределяется через JITSI_BASE_URL в .env.
JITSI_BASE_URL = os.environ.get('JITSI_BASE_URL', 'https://lesson.genurok.ru').rstrip('/')

# JWT-аутентификация на своём сервере Jitsi.
# JITSI_APP_ID  — значение поля "Application ID" в настройках Jitsi (prosody/config.lua, ключ appId).
# JITSI_JWT_SECRET — общий секрет между ЛК и Jitsi-сервером (jitsi.cfg.lua: appSecret).
# Если оба заданы — учитель получает роль moderator автоматически через JWT.
# Для meet.jit.si оставьте пустыми (JWT встроенный не поддерживается).
JITSI_APP_ID     = os.environ.get('JITSI_APP_ID', '').strip()
JITSI_JWT_SECRET = os.environ.get('JITSI_JWT_SECRET', '').strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Cabinet',
    'rest_framework',
    'corsheaders',
    'channels',
    'VideoCalling',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'Cabinet.middleware.SecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Cabinet.middleware.UpdateLastActivityMiddleware',
]

ROOT_URLCONF = 'Cabinet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Cabinet.context_processors.site_urls',
            ],
        },
    },
]

WSGI_APPLICATION = 'Cabinet.wsgi.application'
ASGI_APPLICATION  = 'Cabinet.asgi.application'

# Channel layers — Redis в проде, InMemory в разработке
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

# Database — PostgreSQL в проде, SQLite локально (если DB_PASSWORD не задан)
_db_password = os.environ.get('DB_PASSWORD', '')
if _db_password:
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     os.environ.get('DB_NAME', 'lk_cabinet'),
            'USER':     os.environ.get('DB_USER', 'lk_user'),
            'PASSWORD': _db_password,
            'HOST':     os.environ.get('DB_HOST', 'localhost'),
            'PORT':     os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME':   BASE_DIR / os.environ.get('SQLITE_NAME', 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Ведущий слэш обязателен: иначе в /admin/ браузер запрашивает /admin/static/... и стили не находятся
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Отдаём статику через finders (admin, DRF, STATICFILES_DIRS), даже если collectstatic не заполнял STATIC_ROOT
WHITENOISE_USE_FINDERS = True

# React build — Django отдаёт его в проде
REACT_BUILD_DIR = BASE_DIR.parent / 'frontend' / 'build'
STATICFILES_DIRS = [REACT_BUILD_DIR / 'static'] if (REACT_BUILD_DIR / 'static').exists() else []

# Media files (uploads: homework attachments, answer files, avatars)
MEDIA_URL  = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'mediafiles')))

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Фильтры в боковой панели (Django ≥ 3.2)
admin.AdminSite.enable_nav_sidebar = True

LOGIN_URL           = '/login/'
LOGIN_REDIRECT_URL  = FRONTEND_URL

# CORS — в проде список задаётся через env
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True

_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]

# Общий объём тела запроса (JSON-API, формы)
DATA_UPLOAD_MAX_MEMORY_SIZE = min(
    int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_MB', '3')) * 1024 * 1024,
    10 * 1024 * 1024,
)

# Секрет вызова POST /api/lesson/teacher-joined/ со стороны генератора (заголовок X-Lesson-Webhook-Secret)
LESSON_WEBHOOK_SECRET = os.environ.get('LESSON_WEBHOOK_SECRET', '').strip()

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': os.environ.get('DRF_THROTTLE_USER', '400/minute'),
        'anon': os.environ.get('DRF_THROTTLE_ANON', '60/minute'),
    },
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',   # для загрузки файлов (ДЗ, ответы)
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Лимит размера загружаемых файлов (по умолчанию 20 МБ, в .env — FILE_UPLOAD_MAX_MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('FILE_UPLOAD_MAX_MB', '20')) * 1024 * 1024

if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    _ssl = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() in ('1', 'true', 'yes')
    SECURE_SSL_REDIRECT = _ssl
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True'
    ).lower() in ('1', 'true', 'yes')
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', '0').lower() in ('1', 'true', 'yes')

