# Generated by Django 6.0.2 on 2026-02-14 12:45

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_short', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TagsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_template', ckeditor.fields.RichTextField()),
                ('answer', models.TextField(max_length=500)),
                ('added_at', models.DateTimeField(default=datetime.datetime.today)),
                ('created_by', models.CharField(default='ADMIN')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', related_query_name='task_item', to='Generator.tagslist')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='Generator.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField()),
                ('task_title', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.tasklist'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('created_by', models.CharField(default='ADMIN')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.level')),
                ('var_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
        ),
        migrations.CreateModel(
            name='VariantContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.task')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.variant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
