# Generated by Django 6.0.2 on 2026-02-10 21:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_short', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField()),
                ('task_title', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(max_length=4000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.tasklist')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('created_by', models.CharField(default='ADMIN')),
                ('var_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.subject')),
            ],
        ),
        migrations.CreateModel(
            name='VariantContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.task')),
                ('var_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.variant')),
            ],
        ),
    ]
