# Generated by Django 6.0.2 on 2026-02-11 08:39

import Generator.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='TaskImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_img', models.ImageField(upload_to=Generator.models.task_url)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.task')),
            ],
        ),
    ]
