# Generated by Django 6.0.2 on 2026-02-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_task_added_at_taskimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskImages',
            new_name='TaskImage',
        ),
    ]
