# Generated by Django 6.0.2 on 2026-02-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_variant_share_token_excalidrawboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='Экзамен', max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='task_files'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='created_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='part',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Generator.part'),
        ),
        migrations.DeleteModel(
            name='ExcalidrawBoard',
        ),
    ]
