# Generated by Django 6.0.2 on 2026-02-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0003_rename_taskimages_taskimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskimage',
            old_name='task_id',
            new_name='task',
        ),
    ]
