# Generated by Django 6.0.2 on 2026-02-18 19:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0004_alter_task_task_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_template',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Task text'),
        ),
    ]
