# Generated by Django 6.0.3 on 2026-04-05 16:07

import Cabinet.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default=Cabinet.models.tomorrow)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.subject')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Все руппы',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Учитель'), ('admin', 'Администратор'), ('student', 'Ученик'), ('editor', 'Редактор')], max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cabinet.tariff')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.userprofile')),
            ],
            options={
                'verbose_name': 'Предмет учителя',
                'verbose_name_plural': 'Предметы учителей',
            },
        ),
        migrations.CreateModel(
            name='TeachersStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=50)),
                ('goal', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('1', 'Активный'), ('2', 'На паузе'), ('3', 'Завершил обучение'), ('4', 'Пробный урок')], max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_teachers', to='Cabinet.userprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_students', to='Cabinet.userprofile')),
            ],
            options={
                'verbose_name': 'Ученики',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='TeachersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.userprofile')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Ученики в группе',
            },
        ),
        migrations.CreateModel(
            name='StudentsHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.userprofile')),
            ],
            options={
                'verbose_name': 'ДЗ заданное',
                'verbose_name_plural': 'ДЗ заданное',
            },
        ),
        migrations.CreateModel(
            name='StudentsAnswerImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.userprofile'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_groups', to='Cabinet.userprofile'),
        ),
    ]
