# Generated by Django 6.0.3 on 2026-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0002_userprofile_user_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Смешное слово',
                'verbose_name_plural': 'Смешные слова',
            },
        ),
    ]
