# Generated by Django 6.0.3 on 2026-04-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0005_populate_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentshomework',
            name='status',
            field=models.CharField(choices=[('1', 'Проверено'), ('2', 'Ждёт проверки'), ('3', 'Просрочено')], default='2', max_length=100),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('notification_type', models.CharField(choices=[('submitted', 'Отправил на проверку'), ('check_deadline_soon', 'Подходит срок проверки'), ('low_result_alert', 'Низкие результаты'), ('missed', 'Не сдал в срок')], max_length=20)),
                ('read', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.userprofile')),
            ],
        ),
    ]
