# Generated by Django 6.0.3 on 2026-04-05 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0006_studentshomework_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersstudent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Cabinet.group'),
        ),
        migrations.AddField(
            model_name='teachersstudent',
            name='lesson_type',
            field=models.CharField(choices=[('individual', 'Индивидуальное'), ('group', 'Групповое')], default='individual', max_length=20),
        ),
    ]
