# Generated by Django 6.0.3 on 2026-04-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0007_teachersstudent_group_teachersstudent_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской'), ('other', 'Не указан')], default='other', max_length=10),
        ),
    ]
