# Generated by Django 6.0.3 on 2026-04-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0011_homework_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentshomework',
            options={'verbose_name': 'ДЗ заданное (старое)', 'verbose_name_plural': 'ДЗ заданные (старые)'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='Cabinet.userprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Cabinet.userprofile'),
        ),
    ]
