# Generated by Django 6.0.3 on 2026-04-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0016_homeworkassignment_board_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('submitted', 'Сдал на проверку'), ('check_deadline_soon', 'Подходит срок проверки'), ('low_result_alert', 'Низкие результаты'), ('missed', 'Не сдал в срок'), ('homework_assigned', 'Новое домашнее задание'), ('reviewed', 'ДЗ проверено'), ('revision_requested', 'ДЗ направлено на доработку'), ('teacher_comment', 'Комментарий учителя к ДЗ')], max_length=25),
        ),
        migrations.CreateModel(
            name='TeacherVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('task_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_variants', to='Cabinet.userprofile')),
            ],
            options={
                'verbose_name': 'Вариант учителя',
                'verbose_name_plural': 'Варианты учителей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherVariantStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('1', 'Урок'), ('2', 'Домашнее задание')], default='1')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.userprofile')),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_to', to='Cabinet.teachervariant')),
            ],
            options={
                'verbose_name': 'Заданный вариант',
                'verbose_name_plural': 'Заданные варианты',
                'ordering': ['-variant_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='teachervariant',
            constraint=models.UniqueConstraint(fields=('teacher', 'variant_id'), name='uniq_teacher_variant_pair'),
        ),
    ]
