# Generated by Django 6.0.3 on 2026-04-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0017_alter_notification_notification_type_teachervariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_token', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finsihed_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.userprofile')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.teachervariant')),
            ],
            options={
                'verbose_name': 'Проведённый урок',
                'verbose_name_plural': 'Проведённые уроки',
            },
        ),
    ]
