# Generated by Django 6.0.3 on 2026-04-20 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0018_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='finsihed_at',
            new_name='finished_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_token',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cabinet.teachervariant'),
        ),
        migrations.CreateModel(
            name='LessonInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('ind', 'Индивидуальный'), ('group', 'Групповой')], max_length=10)),
                ('target_id', models.IntegerField()),
                ('target_name', models.CharField(max_length=150)),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('expired', 'Истекло'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('lesson_link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='Cabinet.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_invites', to='Cabinet.userprofile')),
            ],
            options={
                'verbose_name': 'Приглашение на урок',
                'verbose_name_plural': 'Приглашения на уроки',
                'ordering': ['-created_at'],
            },
        ),
    ]
