# Generated by Django 6.0.3 on 2026-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0019_rename_finsihed_at_lesson_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoninvite',
            name='token',
            field=models.CharField(editable=False, max_length=2048, unique=True),
        ),
    ]
