# Generated by Django 6.0.3 on 2026-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0020_alter_lessoninvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoninvite',
            name='lesson_link',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
