# Generated by Django 6.0.3 on 2026-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0024_userprofile_vk_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentshomework',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='studentshomework',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachervariantstudents',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachervariantstudents',
            name='variant_id',
        ),
        migrations.DeleteModel(
            name='StudentsAnswerImg',
        ),
        migrations.DeleteModel(
            name='StudentsHomework',
        ),
        migrations.DeleteModel(
            name='TeacherVariantStudents',
        ),
    ]
