# Generated by Django 6.0.3 on 2026-04-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0027_userprofile_avatar_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlatformConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_code', models.CharField(db_index=True, max_length=64)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(blank=True, default='lk', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_consents', to='Cabinet.userprofile')),
            ],
            options={
                'verbose_name': 'Согласие пользователя',
                'verbose_name_plural': 'Согласия пользователей',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'consent_code'), name='uniq_user_platform_consent')],
            },
        ),
    ]
