# Generated by Django 6.0.3 on 2026-04-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0028_userplatformconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Задано'), ('submitted', 'Сдано на проверку'), ('reviewing', 'На проверке'), ('reviewed', 'Проверено'), ('revision', 'На доработке'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='reviewed', max_length=20)),
                ('teacher_comment', models.TextField(blank=True, default='')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='student_reports/')),
                ('report_filename', models.CharField(blank=True, default='', max_length=255)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_report', to='Cabinet.homeworkassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports', to='Cabinet.userprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lesson_reports', to='Cabinet.userprofile')),
            ],
            options={
                'verbose_name': 'Отчёт по ученику',
                'verbose_name_plural': 'Отчёты по ученикам',
                'ordering': ['-generated_at'],
            },
        ),
    ]
