# Generated by Django 6.0.2 on 2026-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0003_part_tags_task_files_alter_variant_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_template',
            field=models.TextField(max_length=2000),
        ),
    ]
