# Generated by Django 6.0.2 on 2026-02-19 18:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0005_alter_task_task_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Task answer'),
        ),
    ]
