# Generated by Django 6.0.2 on 2026-02-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0006_task_author_alter_task_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_rus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
