# Generated by Django 6.0.2 on 2026-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0007_level_level_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_rus',
            field=models.CharField(default='', max_length=50),
        ),
    ]
