# Generated by Django 5.2.11 on 2026-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0008_alter_level_level_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.TextField(),
        ),
    ]
