# Generated by Django 5.2.11 on 2026-02-24 17:00
# Таблицы уже могут существовать в БД — сначала помечаем миграцию по состоянию,
# при необходимости примените: python manage.py migrate Generator 0010 --fake

import django.db.models.deletion
from django.db import migrations, models


def create_inf_ege_19_21_group(apps, schema_editor):
    Subject = apps.get_model("Generator", "Subject")
    Level = apps.get_model("Generator", "Level")
    LinkedTaskGroup = apps.get_model("Generator", "LinkedTaskGroup")
    subject = Subject.objects.filter(subject_short="inf").first()
    level = Level.objects.filter(level="ege").first()
    if subject and level and not LinkedTaskGroup.objects.filter(subject=subject, level=level).exists():
        LinkedTaskGroup.objects.create(subject=subject, level=level, task_numbers=[19, 20, 21])


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0009_alter_task_answer"),
    ]

    operations = [
        # Обновляем только состояние миграций, не трогаем БД (таблицы уже есть)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="TaskGroup",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("level", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Generator.level")),
                        ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Generator.subject")),
                    ],
                    options={"verbose_name": "Группа заданий"},
                ),
                migrations.CreateModel(
                    name="LinkedTaskGroup",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("task_numbers", models.JSONField(default=list)),
                        ("level", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Generator.level")),
                        ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Generator.subject")),
                    ],
                    options={
                        "verbose_name": "Связанная группа номеров",
                        "unique_together": {("subject", "level")},
                    },
                ),
                migrations.CreateModel(
                    name="TaskGroupMember",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("task_number", models.IntegerField()),
                        ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Generator.task")),
                        ("task_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Generator.taskgroup")),
                    ],
                    options={
                        "verbose_name": "Задание в группе",
                        "ordering": ["task_number"],
                        "unique_together": {("task_group", "task_number")},
                    },
                ),
            ],
            database_operations=[],  # таблицы уже созданы, в БД ничего не делаем
        ),
        migrations.RunPython(create_inf_ege_19_21_group, migrations.RunPython.noop),
    ]
