# Generated by Django 5.2.11 on 2026-02-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0010_taskgroup_linkedtaskgroup_taskgroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
