# Generated by Django 5.2.11 on 2026-04-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0033_announcement_theme_worksheet_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='button_url',
            field=models.CharField(blank=True, help_text='Полный URL или путь на сайте, например /oge', max_length=500, verbose_name='Ссылка кнопки'),
        ),
    ]
