# Generated by Django 5.2.11 on 2026-04-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0034_alter_announcement_button_url'),
        ('Generator', '0034_error_report'),
    ]

    operations = [
    ]
