# Generated by Django 5.2.11 on 2026-04-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0036_merge_20260406_1456'),
        ('Generator', '0038_lessonroom_lesson_ended_at'),
    ]

    operations = [
    ]
